"""add_ea_mode_tables

Revision ID: 07c541973018
Revises: c44aad39ca54
Create Date: 2026-02-10 17:39:39.481654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07c541973018'
down_revision: Union[str, None] = 'c44aad39ca54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('briefs', sa.Column('executive_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_briefs_executive_id'), 'briefs', ['executive_id'], unique=False)

    # Create executives table
    op.create_table(
        'executives',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=True),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('google_calendar_ids', sa.JSON(), nullable=False),
        sa.Column('timezone', sa.String(length=50), nullable=True),
        sa.Column('delivery_time', sa.String(length=5), nullable=True),
        sa.Column('delivery_schedule', sa.JSON(), nullable=True),
        sa.Column('email_recipient', sa.String(length=255), nullable=True),
        sa.Column('content_depth', sa.String(length=20), nullable=True),
        sa.Column('time_window_hours', sa.Integer(), nullable=True),
        sa.Column('enable_ai_prep', sa.Boolean(), nullable=True),
        sa.Column('enable_news', sa.Boolean(), nullable=True),
        sa.Column('enable_meeting_history', sa.Boolean(), nullable=True),
        sa.Column('enable_affinity_data', sa.Boolean(), nullable=True),
        sa.Column('enable_web_enrichment', sa.Boolean(), nullable=True),
        sa.Column('filter_require_non_owner', sa.Boolean(), nullable=True),
        sa.Column('filter_external_only', sa.Boolean(), nullable=True),
        sa.Column('filter_exclude_recurring', sa.Boolean(), nullable=True),
        sa.Column('focus_area', sa.Text(), nullable=True),
        sa.Column('linkedin_url', sa.String(length=500), nullable=True),
        sa.Column('internal_domains', sa.JSON(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executives_id'), 'executives', ['id'], unique=False)
    op.create_index(op.f('ix_executives_email'), 'executives', ['email'], unique=True)

    # Create meeting_annotations table
    op.create_table(
        'meeting_annotations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('executive_id', sa.Integer(), nullable=False),
        sa.Column('event_id', sa.String(length=255), nullable=False),
        sa.Column('priority', sa.String(length=20), nullable=True),
        sa.Column('prep_notes', sa.Text(), nullable=True),
        sa.Column('action_before_meeting', sa.Text(), nullable=True),
        sa.Column('post_meeting_notes', sa.Text(), nullable=True),
        sa.Column('decisions_made', sa.Text(), nullable=True),
        sa.Column('action_items', sa.JSON(), nullable=True),
        sa.Column('follow_up_required', sa.Boolean(), nullable=True),
        sa.Column('follow_up_date', sa.DateTime(), nullable=True),
        sa.Column('follow_up_notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meeting_annotations_id'), 'meeting_annotations', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_annotations_executive_id'), 'meeting_annotations', ['executive_id'], unique=False)
    op.create_index(op.f('ix_meeting_annotations_event_id'), 'meeting_annotations', ['event_id'], unique=False)

    # Create person_relationships table
    op.create_table(
        'person_relationships',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('executive_id', sa.Integer(), nullable=False),
        sa.Column('person_email', sa.String(length=255), nullable=False),
        sa.Column('person_name', sa.String(length=255), nullable=True),
        sa.Column('person_company', sa.String(length=255), nullable=True),
        sa.Column('relationship_strength', sa.String(length=20), nullable=True),
        sa.Column('relationship_status', sa.String(length=50), nullable=True),
        sa.Column('relationship_notes', sa.Text(), nullable=True),
        sa.Column('personal_details', sa.JSON(), nullable=True),
        sa.Column('linkedin_url', sa.String(length=500), nullable=True),
        sa.Column('first_met_date', sa.DateTime(), nullable=True),
        sa.Column('last_met_date', sa.DateTime(), nullable=True),
        sa.Column('total_meetings', sa.Integer(), nullable=True),
        sa.Column('last_follow_up', sa.DateTime(), nullable=True),
        sa.Column('next_follow_up', sa.DateTime(), nullable=True),
        sa.Column('follow_up_cadence_days', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_person_relationships_id'), 'person_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_person_relationships_executive_id'), 'person_relationships', ['executive_id'], unique=False)
    op.create_index(op.f('ix_person_relationships_person_email'), 'person_relationships', ['person_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop EA mode tables
    op.drop_index(op.f('ix_person_relationships_person_email'), table_name='person_relationships')
    op.drop_index(op.f('ix_person_relationships_executive_id'), table_name='person_relationships')
    op.drop_index(op.f('ix_person_relationships_id'), table_name='person_relationships')
    op.drop_table('person_relationships')

    op.drop_index(op.f('ix_meeting_annotations_event_id'), table_name='meeting_annotations')
    op.drop_index(op.f('ix_meeting_annotations_executive_id'), table_name='meeting_annotations')
    op.drop_index(op.f('ix_meeting_annotations_id'), table_name='meeting_annotations')
    op.drop_table('meeting_annotations')

    op.drop_index(op.f('ix_executives_email'), table_name='executives')
    op.drop_index(op.f('ix_executives_id'), table_name='executives')
    op.drop_table('executives')

    # Drop executive_id column from briefs
    op.drop_index(op.f('ix_briefs_executive_id'), table_name='briefs')
    op.drop_column('briefs', 'executive_id')
    # ### end Alembic commands ###
