"""Add dashboard features: extend UserSettings, add FilterPreset and BriefMetrics tables

Revision ID: c44aad39ca54
Revises: 
Create Date: 2026-02-10 16:07:46.728244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c44aad39ca54'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brief_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brief_id', sa.Integer(), nullable=False),
    sa.Column('meetings_processed', sa.Integer(), nullable=True),
    sa.Column('meetings_enriched', sa.Integer(), nullable=True),
    sa.Column('meetings_with_ai_prep', sa.Integer(), nullable=True),
    sa.Column('affinity_api_calls', sa.Integer(), nullable=True),
    sa.Column('openai_tokens_used', sa.Integer(), nullable=True),
    sa.Column('news_api_calls', sa.Integer(), nullable=True),
    sa.Column('linkedin_found', sa.Integer(), nullable=True),
    sa.Column('news_articles_found', sa.Integer(), nullable=True),
    sa.Column('company_data_found', sa.Integer(), nullable=True),
    sa.Column('generation_time_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brief_metrics_brief_id'), 'brief_metrics', ['brief_id'], unique=False)
    op.create_index(op.f('ix_brief_metrics_id'), 'brief_metrics', ['id'], unique=False)
    op.create_table('filter_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filter_presets_id'), 'filter_presets', ['id'], unique=False)
    op.create_index(op.f('ix_filter_presets_user_id'), 'filter_presets', ['user_id'], unique=False)
    op.add_column('user_settings', sa.Column('delivery_schedule', sa.JSON(), nullable=True))
    op.add_column('user_settings', sa.Column('content_depth', sa.String(length=20), nullable=True))
    op.add_column('user_settings', sa.Column('time_window_hours', sa.Integer(), nullable=True))
    op.add_column('user_settings', sa.Column('enable_ai_prep', sa.Boolean(), nullable=True))
    op.add_column('user_settings', sa.Column('enable_news', sa.Boolean(), nullable=True))
    op.add_column('user_settings', sa.Column('enable_meeting_history', sa.Boolean(), nullable=True))
    op.add_column('user_settings', sa.Column('enable_affinity_data', sa.Boolean(), nullable=True))
    op.add_column('user_settings', sa.Column('enable_web_enrichment', sa.Boolean(), nullable=True))
    op.add_column('user_settings', sa.Column('filter_require_non_owner', sa.Boolean(), nullable=True))
    op.add_column('user_settings', sa.Column('filter_external_only', sa.Boolean(), nullable=True))
    op.add_column('user_settings', sa.Column('filter_exclude_recurring', sa.Boolean(), nullable=True))
    op.add_column('user_settings', sa.Column('max_news_articles', sa.Integer(), nullable=True))
    op.add_column('user_settings', sa.Column('talking_points_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'talking_points_enabled')
    op.drop_column('user_settings', 'max_news_articles')
    op.drop_column('user_settings', 'filter_exclude_recurring')
    op.drop_column('user_settings', 'filter_external_only')
    op.drop_column('user_settings', 'filter_require_non_owner')
    op.drop_column('user_settings', 'enable_web_enrichment')
    op.drop_column('user_settings', 'enable_affinity_data')
    op.drop_column('user_settings', 'enable_meeting_history')
    op.drop_column('user_settings', 'enable_news')
    op.drop_column('user_settings', 'enable_ai_prep')
    op.drop_column('user_settings', 'time_window_hours')
    op.drop_column('user_settings', 'content_depth')
    op.drop_column('user_settings', 'delivery_schedule')
    op.drop_index(op.f('ix_filter_presets_user_id'), table_name='filter_presets')
    op.drop_index(op.f('ix_filter_presets_id'), table_name='filter_presets')
    op.drop_table('filter_presets')
    op.drop_index(op.f('ix_brief_metrics_id'), table_name='brief_metrics')
    op.drop_index(op.f('ix_brief_metrics_brief_id'), table_name='brief_metrics')
    op.drop_table('brief_metrics')
    # ### end Alembic commands ###
