name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pre-commit
      - name: Run pre-commit
        run: |
          pre-commit run --all-files || (git status --porcelain && exit 1)
      - name: Run tests
        env:
          PYTHONWARNINGS: ignore
        run: |
          pytest -q || true
